apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
spec:
  selector:
    matchLabels:
      app: pgadmin4
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: pgadmin4
          #image: dpage/pgadmin4:5
          image: dpage/pgadmin4:7.1
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: pgadmin4@pgadmin.org
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pgadmin4-storage
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin4-storage
          hostPath:
            path: /data/pgadmin4
