apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /hosthome/chris/Documents/kubernetes/labs/shoppinglist-webapp-demo/storage

